"""FieldProof domain layer.

Deterministic core: models, state machine, claim compatibility, reconciliation,
policy and authorization. Nothing here calls a model or touches the network,
which is what makes the invariants in tests/ meaningful (PRD 31).
"""

from .enums import (
    ActionType,
    ClaimStatus,
    ClaimType,
    ConfidenceBand,
    ConflictSeverity,
    ConflictStatus,
    ConflictType,
    DecisionAction,
    DecisionStatus,
    EventType,
    EvidenceType,
    JobStatus,
    LinkRelationship,
    PolicyOutcome,
    RequirementStatus,
    RequirementType,
)
from .models import (
    Claim,
    ClaimEvidenceLink,
    Conflict,
    Decision,
    Event,
    Evidence,
    Job,
    JobState,
    Observation,
    ReceiptExtraction,
    ReceiptLineItem,
    Requirement,
)

__all__ = [
    "ActionType",
    "Claim",
    "ClaimEvidenceLink",
    "ClaimStatus",
    "ClaimType",
    "ConfidenceBand",
    "Conflict",
    "ConflictSeverity",
    "ConflictStatus",
    "ConflictType",
    "Decision",
    "DecisionAction",
    "DecisionStatus",
    "Event",
    "EventType",
    "Evidence",
    "EvidenceType",
    "Job",
    "JobState",
    "JobStatus",
    "LinkRelationship",
    "Observation",
    "PolicyOutcome",
    "ReceiptExtraction",
    "ReceiptLineItem",
    "Requirement",
    "RequirementStatus",
    "RequirementType",
]
